version: '2'
services:
    trevgerr-app:
        image: trevgerr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trevgerr-mysql:3306/trevgerr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trevgerr-mysql:
        extends:
            file: mysql.yml
            service: trevgerr-mysql
